### ISSUE TITLE
Cityscapes Imagesets

### ISSUE THREAD

**Issue by Thomas-Kb** [kinredon/Harmonious-Teacher#18]
Dear Author, 
I have a question regarding the data for cityscapes -> foggy-cityscapes experiment: 
Which ImageSets did you use for the source and the target domain? Did you use all 2,975 images in both the source and the target domain or did you split it? If so, how did you split it?
Thanks and best regards

**Comment by kinredon** [comment]
@Thomas-Kb Following previous works, we train the model using the labeled train split of cityscapes (2975 images) and the unlabeled train split of foggy-cityscapes (2975 images). The model is evaluated on the validation set (500 images) of foggy-cityscapes.

**Comment by Thomas-Kb** [comment]
Correct me if I'm wrong, but in the train split of foggy cityscapes are the same images as cityscapes only with fog, right? 
I also could not find annotations (i.e., a separate "gtFine" folder) for the foggy annotations. 
So, I guess you used the same annotations and the same images (only with fog) for your cityscapes->foggy-cityscapes domain adaption?

**Comment by kinredon** [comment]
@Thomas-Kb Yes. The foggy cityscapes actually have the same annotations as the original cityscapes because the foggy effect is added to the cityscapes. However, the DAOD methods do not utilize this prior knowledge to assist in model training, and the target labels are not available to the model despite having the same annotations.

**Comment by Thomas-Kb** [comment]
Thanks for the clarification!
